### ISSUE TITLE
Question about ConvMAE-v2

### ISSUE THREAD

**Issue by z-jiaming** [Alpha-VL/ConvMAE#19]
Thank you for your excellent work!

When I load ConvMAE-v2-Base pretrained checkpoints [https://drive.google.com/file/d/1gykVKNDlRn8eiuXk5bUj1PbSnHXFzLnI/view?usp=sharing], it has cls_token parameter, which not in models_convmae.py.

Does ConvMAE-v2 model different from models_convmae.py in some details, thanks!

**Comment by gaopengpjlab** [comment]
Compared with ConvMAE-V1, ConvMAE-V2 add an extra CLS token. We will share paper and code soon.

**Comment by z-jiaming** [comment]
Thanks for your reply!
But I'm confused that if [models_convmae.py](https://github.com/Alpha-VL/ConvMAE/blob/main/models_convmae.py) and [models_convvit.py](https://github.com/Alpha-VL/ConvMAE/blob/main/models_convvit.py) is ConvMAE-v1, why your released pretrained checkpoints for ConvMAE_Base not have mask_token, stage1_output and stage2_output, but ConvMAE-v2 provided? Did you filter them because models_convvit dosen't need them?

Thanks!!

**Comment by gaopengpjlab** [comment]
We filter out mask_token, stage1_output and stage2_output from the ConvMAE Base checkpoint. ConvMAE-V2 do not need mask_token, stage1_output and stage2_output.

**Comment by z-jiaming** [comment]
Thanks a lot !
Looking forward to ConvMAE-v2 !
