### ISSUE TITLE
Will the code of MAE pretrain be updated recently?

### ISSUE THREAD

**Issue by KevinLongkk** [Alpha-VL/ConvMAE#2]

**Comment by gaopengpjlab** [comment]
We will release detection code first (within 10 days), then segmentation code (within 15 days), then pretrain code (within 20 days).

**Comment by gaopengpjlab** [comment]
Detection released just now. We are working on segmentation and pretrain. Thanks for your patience.

**Comment by TeleeMa** [comment]
@KevinLongkk We have uploaded the pretrained codes. Thanks for your attention.
