### ISSUE TITLE
Train on 

### ISSUE THREAD

**Issue by zqyJason** [Alpha-VL/ConvMAE#21]
Could you provide a tutorial on how to train and finetune with custom dataset? And how to modify the input image size during the detection, the current code seems not to support custom image size.

**Comment by gaopengpjlab** [comment]
Please refer to this repo for object detection with variable image size https://github.com/OpenGVLab/Official-ConvMAE-Det

**Comment by zqyJason** [comment]
> Please refer to this repo for object detection with variable image size https://github.com/OpenGVLab/Official-ConvMAE-Det

Thank you !
