### ISSUE TITLE
how many gpus and which type of gpu are needed for pretraining, down-stream task finetuning?

### ISSUE THREAD

**Issue by wenmengzhou** [Alpha-VL/ConvMAE#4]
specifically, gpu type,  gpu number and gpu training time for pretraining, detection training and segmentation training

**Comment by gaopengpjlab** [comment]
Pretraining is done with 8 A6000 with 48G GPU memory
Detection is done with 8 A100 with 80G GPU memory which tooks around 1 day and 5 hours
Segmentation is done with 8 V100 with 32G GPU memory

**Comment by wenmengzhou** [comment]
> Pretraining is done with 8 A6000 with 48G GPU memory Detection is done with 8 A100 with 80G GPU memory which tooks around 1 day and 5 hours Segmentation is done with 8 V100 with 32G GPU memory

thanks

**Comment by gaopengpjlab** [comment]
Please check FastConvMAE for a fast implementation of pretraining and also benchmarking  different MIM paradigm.

**Comment by wenmengzhou** [comment]
> Please check FastConvMAE for a fast implementation of pretraining and also benchmarking different MIM paradigm.

pls provide a link？  Google failed to find it

**Comment by gaopengpjlab** [comment]
https://github.com/Alpha-VL/FastConvMAE. Code (one or two days) and paper (one week) will be released soon.
